workspace_root: &workspace_root /go/src/github.com/gruntwork-io/terragrunt

defaults: &defaults
  working_directory: *workspace_root
  docker:
    - image: 087285199408.dkr.ecr.us-east-1.amazonaws.com/circle-ci-test-image-base:go1.13

version: 2
jobs:
  # We're running unit tests separately from integration tests - with no parallelization.
  # With heavy parallelization coupled with re-use of test fixtures we've witnessed slight
  # instability with the tests. The unit tests are fast to execute, so there is negligible
  # performance penalty.
  unit_test:
    <<: *defaults
    steps:
      - checkout
      - run: gruntwork-install --binary-name 'terratest_log_parser' --repo 'https://github.com/gruntwork-io/terratest' --tag 'v0.13.8'
      - run:
          command: |
            mkdir -p logs
            run-go-tests --parallelism 1 --packages "$(go list ./... | grep -v /test | tr '\n' ' ')"  | tee logs/unit.log
      - run:
          command: terratest_log_parser --testlog logs/unit.log --outputdir logs
          when: always
      - store_artifacts:
          path: logs
      - store_test_results:
          path: logs

  integration_test:
    <<: *defaults
    steps:
      - checkout
      - run: gruntwork-install --binary-name 'terratest_log_parser' --repo 'https://github.com/gruntwork-io/terratest' --tag 'v0.13.8'
      # Make GCP Service Account creds available as a file
      - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: echo 'export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json' >> $BASH_ENV
      - run:
          command: |
            mkdir -p logs
            run-go-tests --packages "$(go list ./... | grep /test | tr '\n' ' ')" | tee logs/integration.log
      - run:
          command: terratest_log_parser --testlog logs/integration.log --outputdir logs
          when: always
      - store_artifacts:
          path: logs
      - store_test_results:
          path: logs

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run: build-go-binaries --app-name terragrunt --dest-path bin --ld-flags "-X main.VERSION=$CIRCLE_TAG"
      - persist_to_workspace:
          root: *workspace_root
          paths: bin

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run: cd bin && sha256sum * > SHA256SUMS
      - run: upload-github-release-assets bin/*

workflows:
  version: 2
  build-and-test:
    jobs:
      - unit_test:
          filters:
            tags:
              only: /^v.*/
      - integration_test:
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - unit_test
            - integration_test
          filters:
            tags:
              only: /^v.*/

      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - unit_test
      - integration_test
